name: LobotomPlugin
version: '1.0-SNAPSHOT'
main: hibikero.lobotomplugin.LobotomPlugin
api-version: '1.16'
description: 自定义生物插件

commands:
  spawnmob:
    description: 生成自定义生物
    usage: /<command> <生物ID>

  getsan:
    description: 查看玩家的SAN值
    usage: /<command> <玩家名称>
  san:
    description:
  LoBoGet:
    description:

